"""empty message

Revision ID: 27806857c58d
Revises: 
Create Date: 2018-11-08 18:44:25.781288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27806857c58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookloans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookloans',
    sa.Column('loanid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bookid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loanerid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checkoutdate', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('returndate', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
